services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    volumes:
      # mount source code
      - .:/app

      # giữ node_modules trong container
      - node_modules:/app/node_modules

    environment:
      NODE_ENV: development

    command: npm run dev

    networks:
      - app-net

volumes:
  node_modules:

name: frontend-admin

networks:
  app-net:
    driver: bridge
